import Navigation from "./component/Navigation";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "./component/Navbar";
// import Layout from './component/Layout'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
    
      </Head>
    </div>
  );
}
