import Head from "next/head";
import styles from "../styles/Home.module.css";
// import Layout from './component/Layout'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TT ELD | ELD Compliance Solution | Asset Tracking | Fleet ...</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://o.remove.bg/downloads/2004e0cc-4bcb-4058-9eb6-8aa324a873f8/tt_eld-removebg-preview.png"
        />

        
      </Head>
    </div>
  );
}
